CameoMvc/CameoMvc/Areas/SYS/Controllers/SYS990Controller.cs
using CameoMvc.Areas.SYS.Models;
using CameoMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CameoMvc.Areas.SYS.Controllers
{
    public class SYS990Controller : Controller
    {
        // GET: SYS/SYS990
        public ActionResult Index()
        {
            string MSG = string.Empty;
            M_SYS990 iData = new M_SYS990();
            M_SYS990 oData = null;
            //FM_SYS990 EXE = new FM_SYS990();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            try
            {
                if (Request.ServerVariables["HTTP_USER_AGENT"] != null)
                    iData.USER_ANGET = Request.ServerVariables["HTTP_USER_AGENT"];


                iData.BROWSER = FM_SYS.DetectBrowser(Request);
            }
            catch (Exception ex)
            {
                MSG = "例外錯誤"
                    + Environment.NewLine + string.Format("功能:{0}", FUNC)
                    + Environment.NewLine + string.Format("訊息:{0}", ex.Message.Replace("'", "").Replace("\r\n", ""));
            }
            finally
            {
                if (MSG?.Length > 0)
                {
                    MSG = MSG.Replace("\r\n", "\\r\\n");
                    TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                }
                else
                {
                    TempData["msg"] = "";
                }

                //操作紀錄
                FM_SYS.Operation_Record(new OperationRecord
                {
                    PROGRAM = FUNC.Substring(0, 3),
                    FUNCTION = FUNC,
                    DLL_FILENAME = string.Format("{0}/{1}/{2}", FUNC.Substring(0, 3), FUNC, ACTION),
                    USER_ID = oData.USER_ID,
                    USE_TYPE = OperationType.Q,
                    REMORK = oData == null || oData.FLAG ? "" : oData.ERR
                });
            }

            ModelState.Clear();
            return View(iData);
        }
    }
}

CameoMvc/CameoMvc/Areas/SYS/Views/SYS990/Index.cshtml
@using CameoMvc.Areas.SYS.Models;
@model M_SYS990
@Html.Raw(TempData["msg"])

@{
    //預設正式環境背景
    var Style_body = "background-color: #FFFFFF;";

    //判斷測試環境背景
    if (Model.ENV_T)
    {
        Style_body = "background-color: #FFD800;";
    }
}

<div id="div_content" style="@Style_body" class="content-wrapper px-1 py-2">
    <section class="content">
        @using (Html.BeginForm("Index", "SYS990", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.FLAG)
            @Html.HiddenFor(model => model.FAB_ID)
            @Html.HiddenFor(model => model.USER_ID)

            <div> @Html.DisplayFor(model => model.USER_NO) </div>
            <div> @Html.DisplayFor(model => model.USER_NAME) </div>
            <hr size="20" color="blue">
            <!--判斷是否為行動裝置開啟網頁-->
            <div> USER_ANGET：@Html.DisplayFor(model => model.USER_ANGET) </div>
            <hr size="20" color="blue">
            <div> BROWSER：@Html.DisplayFor(model => model.BROWSER) </div>
            <hr size="20" color="blue">
            <div> @Html.CheckBoxFor(model => model.PHON) 手機</div>
            <div> @Html.CheckBoxFor(model => model.MOBL) 行動裝置</div>
            <hr size="20" color="blue">
            <div>
                <input id="SYS990_chkPhone" type="checkbox" /> 手機
            </div>
            <div>
                <input id="SYS990_chkMobil" type="checkbox" /> 行動裝置
            </div>
        }
    </section>
</div>
<script type="text/javascript">
    var isPhone = checkPhone();
    var isMobil = checkMobile();
    $('#SYS990_chkPhone').prop('checked', isPhone);
    $('#SYS990_chkMobil').prop('checked', isMobil);
</script>