CameoMvc/CameoMvc/Areas/SMT/Controllers/SMT002Controller.cs
using CameoMvc.Areas.SMT.Models;
using CameoMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CameoMvc.Areas.SMT.Controllers
{
    public class SMT002Controller : Controller
    {
        // GET: SMT/SMT002
        public ActionResult Index()
        {
            string MSG = string.Empty;
            M_SMT002 oData = null;
            M_SMT002 iData = new M_SMT002();
            FM_SMT002 EXE = new FM_SMT002();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            try
            {
                //第一次開啟賦予預設值
                iData.QM.sDate = DateTime.Now.AddDays(-1).ToString("yyyy/MM/dd");
                iData.QM.eDate = DateTime.Now.AddDays(-1).ToString("yyyy/MM/dd");
                iData.QM.Timing = true;
                iData.QM.Exception = false;

                //執行查詢
                oData = EXE.QUERY(iData, false);
            }
            catch (Exception ex)
            {
                MSG = "例外錯誤"
                    + Environment.NewLine + string.Format("功能:{0}/{1}", FUNC, ACTION)
                    + Environment.NewLine + string.Format("訊息:{0}", ex.Message.Replace("'", "").Replace("\r\n", ""));
            }
            finally
            {
                if (MSG?.Length > 0)
                {
                    MSG = MSG.Replace("\r\n", "\\r\\n");
                    TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                }
                else
                {
                    TempData["msg"] = "";
                }
                //操作紀錄
                FM_SYS.Operation_Record(new OperationRecord
                {
                    PROGRAM = FUNC.Substring(0, 3),
                    FUNCTION = FUNC,
                    DLL_FILENAME = string.Format("{0}/{1}/{2}", FUNC.Substring(0, 3), FUNC, ACTION),
                    USER_ID = oData.USER_ID,
                    USE_TYPE = OperationType.Q,
                    REMORK = oData == null || oData.FLAG ? string.Empty : oData.ERR
                });
            }

            ModelState.Clear();
            return View(oData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(M_SMT002 iData)
        {
            string MSG = string.Empty;
            M_SMT002 oData = null;
            FM_SMT002 EXE = new FM_SMT002();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            try
            {
                if (string.IsNullOrWhiteSpace(iData.QM.eDate))
                    iData.QM.eDate = iData.QM.sDate;
                //執行查詢
                oData = EXE.QUERY(iData, false);
            }
            catch (Exception ex)
            {
                MSG = "例外錯誤"
                    + Environment.NewLine + string.Format("功能:{0}/{1}", FUNC, ACTION)
                    + Environment.NewLine + string.Format("訊息:{0}", ex.Message.Replace("'", "").Replace("\r\n", ""));
            }
            finally
            {
                if (MSG?.Length > 0)
                {
                    MSG = MSG.Replace("\r\n", "\\r\\n");
                    TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                }
                else
                {
                    TempData["msg"] = "";
                }
                //操作紀錄
                FM_SYS.Operation_Record(new OperationRecord
                {
                    PROGRAM = FUNC.Substring(0, 3),
                    FUNCTION = FUNC,
                    DLL_FILENAME = string.Format("{0}/{1}/{2}", FUNC.Substring(0, 3), FUNC, ACTION),
                    USER_ID = oData.USER_ID,
                    USE_TYPE = OperationType.Q,
                    REMORK = oData == null || oData.FLAG ? string.Empty : oData.ERR
                });
            }

            ModelState.Clear();
            return View(oData);
        }
    }
}

CameoMvc/CameoMvc/Areas/SMT/Views/SMT002/Index.cshtml
@using CameoMvc.Areas.SMT.Models;
@model M_SMT002
@Html.Raw(TempData["msg"])

@{
    //預設正式環境背景
    var Style_body = "background-color: #FFFFFF;";

    //判斷測試環境背景
    if (Model.ENV_T)
    {
        Style_body = "background-color: #FFD800;";
    }
}

<div id="div_content" style="@Style_body" class="content-wrapper px-1 py-2">
    <section class="content">
        @using (Html.BeginForm("Index", "SMT002", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.FLAG)
            @Html.HiddenFor(model => model.FAB_ID)
            @Html.HiddenFor(model => model.USER_ID)
            @Html.HiddenFor(model => model.USER_NO)
            @Html.HiddenFor(model => model.USER_NAME)
            @Html.HiddenFor(model => model.ERR)

            @Html.Partial("_Query", Model)

            if (Model.LIST_CHART != null)
            {
                foreach (M_CHART mChart in Model.LIST_CHART)
                {
                    @Html.Partial("_Chart", mChart)
                }
            }
        }
    </section>
</div>

CameoMvc/CameoMvc/Areas/SMT/Views/SMT002/_Chart.cshtml
@using CameoMvc.Areas.SMT.Models;
@model M_CHART

@{
    ViewBag.Title = "Chart";
    var jsonX = Json.Encode(Model.X_NAME);
    var jsonVALUE = Json.Encode(Model.VALUE);
    var jsonLCL = Json.Encode(Model.LCL);
    var jsonUCL = Json.Encode(Model.UCL);
    var jsonLSL = Json.Encode(Model.LSL);
    var jsonUSL = Json.Encode(Model.USL);
    var jsonDC_UNIT = Json.Encode(Model.DC_UNIT);
    var jsonY = Json.Encode(Model.Y_NAME);
    var divChart_Style = Model.DC_NAME == "RH" ? "" : "display:none";
    var iRadius = Model.VALUE.Length > 24 ? 1 : 5;
    var iHoverRadius = Model.VALUE.Length > 24 ? 1 : 10;
}

<div id="divChart_@Model.DC_NAME" style="@divChart_Style">
    <canvas id="myChart_@Model.DC_NAME" width="200" height="48"></canvas>
</div>

<script type="text/javascript">
    var ctx = document.getElementById("myChart_@Model.DC_NAME");
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: @Html.Raw(jsonX),
            datasets: [{
                label: @Html.Raw(jsonY),
                data: @Html.Raw(jsonVALUE),
                borderColor: 'rgb(255,135,20)',
                pointStyle: "circle",
                pointBackgroundColor: 'rgb(255,228,202)',
                pointRadius: @Html.Raw(iRadius),
                pointHoverRadius: @Html.Raw(iHoverRadius)
            }, {
                label: '下限',
                data: @Html.Raw(jsonLCL),
                fill: false,
                backgroundColor: 'rgba(255,165,0,0.3)',
                borderColor: 'rgb(255,149,202)',
                pointStyle: "circle",
                pointBackgroundColor: 'rgb(255,217,236)',
                pointRadius: @Html.Raw(iRadius),
                pointHoverRadius: @Html.Raw(iHoverRadius)
            }, {
                label: '上限',
                data: @Html.Raw(jsonUCL),
                fill: false,
                backgroundColor: 'rgba(255,165,0,0.3)',
                borderColor: 'rgb(130,217,0)',
                pointStyle: "circle",
                pointBackgroundColor: 'rgb(222,255,172)',
                pointRadius: @Html.Raw(iRadius),
                pointHoverRadius: @Html.Raw(iHoverRadius)
            }]
        }
    });
</script>

CameoMvc/CameoMvc/Areas/SMT/Views/SMT002/_Query.cshtml
@using CameoMvc.Areas.SMT.Models;
@model M_SMT002

@{
    <!-- 抬頭功能名稱 -->
    var TitleText = Model.FUNC_NAME + "(" + Model.FUNC + ")";

    <!-- 判斷是否為行動裝置，以採用對應的樣式 -->
    //預設為展開
    var divCard_Style = "card";
    var imgCard_Style = "fas fa-minus";

    //行動裝置，改為縮合
    if (Model.PHON)
    {
        divCard_Style = "card collapsed-card";
        imgCard_Style = "fas fa-plus";
    }
}
<div id="divCard" class="@divCard_Style">
    <div class="card-header bg-gradient-primary">
        <h3 class="card-title">@TitleText</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="收合">
                <i class="@imgCard_Style"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">防 潮 櫃</div>
                    </div>
                    @Html.DropDownListFor(model => model.QM.Device, Model.DLL_DEVS, new { @class = "form-control input-md" })
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <div id="bootstrap-datepicker" class="input-group date">
                    <div class="input-group-prepend">
                        <div class="input-group-text">查詢日期</div>
                    </div>
                    @Html.TextBoxFor(model => model.QM.sDate, new { @class = "form-control datetimepicker-input", @placeholder = "YYYY/MM/DD" })
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            @Html.CheckBoxFor(model => model.QM.Timing, new { @class = "form-check" })
                        </div>
                    </div>
                    <input type="text" class="form-control" value="定時紀錄模式" disabled="disabled" />
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            @Html.CheckBoxFor(model => model.QM.Exception, new { @class = "form-check" })
                        </div>
                    </div>
                    <input type="text" class="form-control" value="異常紀錄模式" disabled="disabled" />
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <button name="button" type="submit" class="btn btn-primary col-12" value="Query">查詢</button>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <input id="rdo_Rh" name="selChart" type="radio" value="RH" checked="checked" />
                        </span>
                        <input type="text" class="form-control" value="濕度紀錄" disabled="disabled" />
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <input id="rdo_Tp" name="selChart" type="radio" value="TP" />
                        </span>
                        <input type="text" class="form-control" value="溫度紀錄" disabled="disabled" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('input[type=radio][name=selChart]').change(function () {
        if (this.value == 'RH') {
            $("#divChart_RH").show();
            $("#divChart_TP").hide();
        }
        else if (this.value == 'TP') {
            $("#divChart_RH").hide();
            $("#divChart_TP").show();
        }
    });

    if (!$.fn.bootstrapDP && $.fn.datepicker && $.fn.datepicker.noConflict) {
        var datepicker = $.fn.datepicker.noConflict();
        $.fn.bootstrapDP = datepicker;
    }
    $.datepicker.setDefaults($.datepicker.regional["zh-TW"]);
    $("#QM_sDate").datepicker({
        dateFormat: "yy/mm/dd",
        showButtonPanel: true,
        changeMonth: true,
        changeYear: true
    });
</script>