CameoMvc/CameoMvc/Areas/QAD/Controllers/QAD001Controller.cs
using CameoMvc.Areas.QAD.Models;
using CameoMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CameoMvc.Areas.QAD.Controllers
{
    public class QAD001Controller : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            string MSG = string.Empty;
            M_QAD001 iData = new M_QAD001();
            M_QAD001 oData = null;
            FM_QAD001 EXE = new FM_QAD001();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            iData.QM.TYPE = QAD001_TYPE.LEND;       //預設操作模式

            try
            {
                oData = EXE.QUERY(iData);
                if (!oData.FLAG)
                {
                    MSG = oData.ERR;
                }
            }
            catch (Exception ex)
            {
                MSG = "例外錯誤"
                     + Environment.NewLine + string.Format("功能:{0}/{1}", FUNC, ACTION)
                     + Environment.NewLine + string.Format("訊息:{0}", ex.Message.Replace("'", "").Replace("\r\n", ""));
            }
            finally
            {
                if (MSG?.Length > 0)
                {
                    MSG = MSG.Replace("\r\n", "\\r\\n");
                    TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                }
                else
                {
                    TempData["msg"] = "";
                }
            }

            ModelState.Clear();

            //是否為行動裝置
            oData.PHON = FM_SYS.IsPhoneDevice(Request);
            oData.MOBL = FM_SYS.IsMobileDevice(Request);

            return View(oData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(M_QAD001 iData, string button)
        {
            string MSG = string.Empty;
            M_QAD001 oData = null;
            FM_QAD001 EXE = new FM_QAD001();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            try
            {
                if (button == "Lend")
                {
                    MSG = EXE.LEND(iData);
                    if (!string.IsNullOrWhiteSpace(MSG))
                        MSG = "借出失敗！" + Environment.NewLine + MSG;
                }
                else if (button == "Back")
                {
                    MSG = EXE.BACK(iData);
                    if (!string.IsNullOrWhiteSpace(MSG))
                        MSG = "歸還失敗！" + Environment.NewLine + MSG;
                }

                iData.QM.TYPE = string.IsNullOrWhiteSpace(iData.QM.CSN) ? QAD001_TYPE.LEND : QAD001_TYPE.ALL;

                oData = EXE.QUERY(iData);

                if (button == "Lend" && string.IsNullOrWhiteSpace(MSG))
                {
                    MSG = "借出成功！";
                }
                else if (button == "Back" && string.IsNullOrWhiteSpace(MSG))
                {
                    MSG = "歸還成功！";
                }
                else if (!oData.FLAG)
                {
                    MSG = oData.ERR;
                }
                if (!string.IsNullOrWhiteSpace(MSG))
                {
                    oData.ERR = MSG;
                }
            }
            catch (Exception ex)
            {
                MSG = "例外錯誤"
                    + Environment.NewLine + string.Format("功能:{0}/{1}", FUNC, ACTION)
                    + Environment.NewLine + string.Format("訊息:{0}", ex.Message.Replace("'", "").Replace("\r\n", ""));
            }
            finally
            {
                if (MSG?.Length > 0)
                {
                    MSG = MSG.Replace("\r\n", "\\r\\n");
                    TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                }
                else
                {
                    TempData["msg"] = "";
                }

                //操作紀錄
                button = button.ToUpper();
                //操作紀錄
                FM_SYS.Operation_Record(new OperationRecord
                {
                    PROGRAM = FUNC.Substring(0, 3),
                    FUNCTION = FUNC,

CameoMvc/CameoMvc/Areas/QAD/Views/QAD001/Index.cshtml
@using CameoMvc.Areas.QAD.Models;
@model M_QAD001
@Html.Raw(TempData["msg"])

@{
    //預設正式環境背景
    var Style_body = "background-color: #FFFFFF;";

    //判斷測試環境背景
    if (Model.ENV_T)
    {
        Style_body = "background-color: #FFD800;";
    }
}

<div id="div_content" style="@Style_body" class="content-wrapper px-1 py-2">
    <section class="content">
        @using (Html.BeginForm("Index", "QAD001", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.FLAG)
            @Html.HiddenFor(model => model.FAB_ID)
            @Html.HiddenFor(model => model.USER_ID)
            @Html.HiddenFor(model => model.USER_NO)
            @Html.HiddenFor(model => model.USER_NAME)
            @Html.HiddenFor(model => model.ERR)

            @Html.Partial("_Query", Model)
            @Html.Partial("_List", Model)
        }
    </section>
</div>

CameoMvc/CameoMvc/Areas/QAD/Views/QAD001/_List.cshtml
@using CameoMvc.Areas.QAD.Models;
@model M_QAD001

@if (@Model.LIST_RM.Count > 0)
{
    if (Model.PHON)
    {
        <div class="row">
            @foreach (var item in Model.LIST_RM)
            {
                var cardStyle = (item.TYPE == QAD001_TYPE.LEND) ? "card card-outline card-dark collapsed-card" : "card card-outline card-info collapsed-card";
                <div id="divCard" class="@cardStyle">
                    <div class="card-header">
                        <h5 class="card-title">@item.MODEL_NAME&nbsp;【@item.PART_NO】</h5>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="收合">
                                <i class="fas fa-plus"></i>
                            </button>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col">棧板：@item.PALLET_NO</div>
                            <div class="col">箱號：@item.CARTON_NO</div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col">借出</div>
                            <div class="col">@item.LEND_USER</div>
                            <div class="col">@item.LEND_TIME</div>
                        </div>
                        @if (!string.IsNullOrWhiteSpace(item.BACK_USER))
                        {
                            <div class="row">
                                <div class="col">歸還</div>
                                <div class="col">@item.BACK_USER</div>
                                <div class="col">@item.BACK_TIME</div>
                            </div>
                        }
                    </div>
                </div>
                @*<blockquote class="table-info">
                        <p class="m-1 text-primary">棧板：@item.PALLET_NO </p>
                        <div style="font-size:smaller">
                            <p class="m-0">箱號：@item.CARTON_NO</p>
                            <p class="m-0">@item.LEND_USER</p>
                            <p class="m-0">@item.LEND_TIME</p>
                        </div>
                    </blockquote>*@
            }
        </div>
    }
    else
    {
        <div id="divList" class="" style="overflow: auto; height:288px;">
            <table id="tbList" class='table table-bordered table-hover table-striped'>
                <thead class="thead-dark">
                    <tr>
                        <th nowrap="nowrap" style="text-align:center;width:150px;">箱號</th>
                        <th nowrap="nowrap" style="text-align:center;">棧板號</th>
                        <th nowrap="nowrap" style="text-align:center;">料號</th>
                        <th nowrap="nowrap" style="text-align:center;">機種</th>
                        <th nowrap="nowrap" style="text-align:center;">借出所刷條碼</th>
                        <th nowrap="nowrap" style="text-align:center;">借出人</th>
                        <th nowrap="nowrap" style="text-align:center;">借出時間</th>
                        <th nowrap="nowrap" style="text-align:center;">歸還所刷條碼</th>
                        <th nowrap="nowrap" style="text-align:center;">還刷關聯條碼</th>
                        <th nowrap="nowrap" style="text-align:center;">歸還人</th>
                        <th nowrap="nowrap" style="text-align:center;">歸還時間</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.LIST_RM)
                    {
                        var style = (item.TYPE == QAD001_TYPE.LEND) ? "table-light" : "table-info";
                        <tr class="@style">
                            <td nowrap="nowrap" style="text-align:center;width:150px;">@item.CARTON_NO</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.PALLET_NO</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.PART_NO</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.MODEL_NAME</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.LEND_SN</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.LEND_USER</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.LEND_TIME</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.BACK_SN</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.BACK_REF_SN</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.BACK_USER</td>
                            <td nowrap="nowrap" style="text-align:center;">@item.BACK_TIME</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
}
else
{
    <div class="pager">
        <table>
            <tr class="GridEmptyRowStyle">
                <td>無資料</td>
            </tr>
        </table>
    </div>
}

<style type="text/css">
    #divList {
        margin: 0px;
    }

    #tbList thead tr {
        border: 1px solid #ffffff;
    }

        #tbList thead tr th {
            position: sticky;
            top: -2px; /* 列首永遠固定於上 */
            border: 1px solid #ffffff;
        }

    #tbList tr td:nth-child(2) {
        position: sticky;
        left: 150px; /* 首行永遠固定於左 */
        z-index: 2;
        /* background-color: lightpink; */
    }

    #tbList thead tr th:nth-child(2) {
        position: sticky;
        left: 150px; /* 首行永遠固定於左 */
        z-index: 3;
    }

    #tbList tbody tr td:first-child {
        position: sticky;
        left: 0px; /* 首行永遠固定於左 */
        z-index: 3;
        /* background-color: lightpink; */
    }

    #tbList thead tr th:first-child {
        position: sticky;
        left: 0px; /* 首行永遠固定於左 */
        z-index: 4;
    }
</style>

<script type="text/javascript">
    let available_height = $("#div_content").height() - $("#divCard").outerHeight() - 27;
    let list_height = $("#tbList").outerHeight();
    if (available_height > list_height + 33)
        available_height = list_height + 33;
    $("#divList").height(available_height);
</script>

CameoMvc/CameoMvc/Areas/QAD/Views/QAD001/_Query.cshtml
@using CameoMvc.Areas.QAD.Models;
@model M_QAD001

@{
    <!-- 抬頭功能名稱 -->
    var TitleText = Model.FUNC_NAME + "(" + Model.FUNC + ")";

    <!-- 判斷是否為行動裝置，以採用對應的樣式 -->
    //預設為展開
    var divCard_Style = "card";
    var imgCard_Style = "fas fa-minus";

    //行動裝置，改為縮合
    //if (Model.PHON)
    //{
    //    divCard_Style = "card collapsed-card";
    //    imgCard_Style = "fas fa-plus";
    //}
}

<!-- 導入 QR Code Reader -->
<div id="modal-qr" class="modal fade show" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" width="400">
            <div class="modal-header">
                <!-- 選擇影像來源 -->
                <div id="SelectSrc" style="display:none">
                    <label for="sourceSelect">選擇鏡頭</label>
                    <select id="sourceSelect" style="max-width:400px"></select>
                </div>
                <div id="ChangeSrc">
                    <a class="btn btn-app bg-success">
                        <i class="glyphicon glyphicon-refresh"></i>
                        更換鏡頭
                    </a>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="modal-body">
                <video id="video" width="400" height="300"></video>
            </div>
        </div>
    </div>
</div>

<div id="divCard" class="@divCard_Style">
    <div class="card-header bg-gradient-primary">
        <h3 class="card-title">@TitleText</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="收合">
                <i class="@imgCard_Style"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <!-- 輸入框 -->
        <!-- 當有多個按鍵時，為了不要直接觸發 Submit，要加入 keypressHandle -->
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="input-group">
                    @Html.TextBoxFor(model => model.QM.CSN, new { id = "txt1", @placeholder = "借出箱號或產品序號(CSN)", @class = "form-control", @autofocus = "", @onkeypress = "keypressHandle(event);" })
                    <div id="btnScan1" name="txt1" class="input-group-addon" data-toggle="modal" data-target="#modal-qr">
                        <div class="input-group-text">
                            <span class="fas fa-barcode"></span>
                        </div>
                    </div>
                </div>
                @Html.ValidationMessageFor(model => model.QM.CSN)
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="input-group">
                    @Html.TextBoxFor(model => model.QM.REF, new { id = "txt2", @placeholder = "同棧板上另一箱號或產品序號(CSN)", @class = "form-control" })
                    <div id="btnScan2" name="txt2" class="input-group-addon" data-toggle="modal" data-target="#modal-qr">
                        <div class="input-group-text">
                            <span class="fas fa-barcode"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                <button name="button" type="submit" class="btn btn-primary col-12" value="Query" id="btnQuery">查詢</button>
            </div>
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                <button name="button" type="submit" class="btn btn-success col-12" value="Lend">借出</button>
            </div>
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                <button name="button" type="submit" class="btn btn-danger col-12" value="Back">歸還</button>
            </div>
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                <span class="btn btn-info col fileinput-button dz-clickable">
                    <i class="fas fa-table"></i>
                    @Html.ActionLink("查詢歷史紀錄", "Index", "QAD002", new { area = "QAD" }, new { @style = "color: #FFFFFF;" })
                </span>
                @*<input type="button" class="btn btn-info  col-12" value="查詢歷史紀錄" onclick="location.href='@Url.Action("Index", "QAD002", new { area = "QAD" })'" />*@
            </div>
        </div>
    </div>
</div>