CameoMvc/CameoMvc/Areas/RPT/Controllers/RPT001Controller.cs
using CameoMvc.Areas.RPT.Models;
using CameoMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CameoMvc.Areas.RPT.Controllers
{
    public class RPT001Controller : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            string MSG = string.Empty;
            M_RPT001 iData = new M_RPT001();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            return View(iData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(M_RPT001 iData)
        {
            string MSG = string.Empty;
            M_RPT001 oData = null;
            FM_RPT001 EXE = new FM_RPT001();
            string ACTION = "Index";
            string FUNC = iData.FUNC;
            string FUNC_NAME = iData.FUNC_NAME;

            #region Cookie 基本資料
            //錯誤資料清空
            iData.FLAG = false;
            iData.ERR = string.Empty;

            //取得 Cookie 紀錄資料
            iData.FAB_ID = M_Cookie.GetCookie(SessionKey._FAB_ID);
            iData.USER_ID = M_Cookie.GetCookie(SessionKey._USER_ID);
            iData.USER_NO = M_Cookie.GetCookie(SessionKey._USER_NO);
            iData.USER_NAME = M_Cookie.GetCookie(SessionKey._USER_NAME);

            //Cookie沒紀錄，改取 Session 紀錄資料
            if (string.IsNullOrWhiteSpace(iData.FAB_ID) && Session[SessionKey._FAB_ID] != null)
                iData.FAB_ID = Session[SessionKey._FAB_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_ID) && Session[SessionKey._USER_ID] != null)
                iData.USER_ID = Session[SessionKey._USER_ID].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NO) && Session[SessionKey._USER_NO] != null)
                iData.USER_NO = Session[SessionKey._USER_NO].ToString();
            if (string.IsNullOrWhiteSpace(iData.USER_NAME) && Session[SessionKey._USER_NAME] != null)
                iData.USER_NAME = Session[SessionKey._USER_NAME].ToString();

            //Cookie 或 Session 過期，或沒有資料，導引到登入畫面
            if (string.IsNullOrWhiteSpace(iData.USER_ID))
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
            //Debug用來 預設廠別ID 及 預設使用者ID
            if (string.IsNullOrWhiteSpace(iData.FAB_ID)) iData.FAB_ID = "0";
            if (string.IsNullOrWhiteSpace(iData.USER_ID)) iData.USER_ID = "0"; //MES(Auto)

            //是否為行動裝置
            iData.PHON = FM_SYS.IsPhoneDevice(Request);
            iData.MOBL = FM_SYS.IsMobileDevice(Request);

            //是否為測試環境
            iData.ENV_T = M_DB.dsMes.ConnectionString.Contains("mesdbtest");

            //確認是否有權限，沒有資料，導引到登入畫面
            iData.AUTHORITY = FM_SYS.QueryAuthority(iData.USER_NO, FUNC);
            if (iData.AUTHORITY.Count <= 0)
            {
                //清空最後登入畫面
                M_Cookie.SetCookie(SessionKey._LAST_ACTN, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_CTRL, "", TimeSpan.FromDays(30));
                M_Cookie.SetCookie(SessionKey._LAST_AREA, "", TimeSpan.FromDays(30));

                MSG = string.Format("您沒有開啟『{1}({0})』之權限", FUNC, FUNC_NAME);
                TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            //紀錄登入畫面
            M_Cookie.SetCookie(SessionKey._LAST_ACTN, ACTION, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_CTRL, iData.FUNC, TimeSpan.FromDays(30));
            M_Cookie.SetCookie(SessionKey._LAST_AREA, iData.FUNC.Substring(0, 3), TimeSpan.FromDays(30));
            #endregion

            try
            {
                oData = EXE.Query(iData);
                if (!oData.FLAG)
                {
                    MSG = oData.ERR == null ? string.Empty : oData.ERR;
                }
            }
            catch (Exception ex)
            {
                MSG = "例外錯誤"
                     + Environment.NewLine + string.Format("功能:{0}/{1}", FUNC, ACTION)
                     + Environment.NewLine + string.Format("訊息:{0}", ex.Message.Replace("'", "").Replace("\r\n", ""));
            }
            finally
            {
                if (MSG?.Length > 0)
                {
                    MSG = MSG.Replace("\r\n", "\\r\\n");
                    TempData["msg"] = string.Format("<script>alert('{0}');</script>", MSG);
                }
                else
                {
                    TempData["msg"] = string.Empty;
                }

                //操作紀錄
                FM_SYS.Operation_Record(new OperationRecord
                {
                    PROGRAM = FUNC.Substring(0, 3),
                    FUNCTION = FUNC,
                    DLL_FILENAME = string.Format("{0}/{1}/{2}", FUNC.Substring(0, 3), FUNC, ACTION),
                    USER_ID = oData.USER_ID,
                    USE_TYPE = OperationType.Q,
                    REMORK = oData == null || oData.FLAG ? string.Empty : oData.ERR
                });
            }

            ModelState.Clear();
            return View(oData);
        }
    }
}

CameoMvc/CameoMvc/Areas/RPT/Views/RPT001/Index.cshtml
@using CameoMvc.Areas.RPT.Models;
@model M_RPT001
@Html.Raw(TempData["msg"])

@{
    //預設正式環境背景
    var Style_body = "background-color: #FFFFFF;";

    //判斷測試環境背景
    if (Model.ENV_T)
    {
        Style_body = "background-color: #FFD800;";
    }
}

<div style="@Style_body" class="content-wrapper px-2 py-2">
    <div id="div_content">
        <section class="content">
            @using (Html.BeginForm("Index", "RPT001", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()

                @Html.HiddenFor(model => model.FLAG)
                @Html.HiddenFor(model => model.ERR)
                @Html.HiddenFor(model => model.FAB_ID)
                @Html.HiddenFor(model => model.USER_ID)
                @Html.HiddenFor(model => model.USER_NO)
                @Html.HiddenFor(model => model.USER_NAME)

                @Html.Partial("_Query", Model)
                @Html.Partial("_List", Model)
            }
        </section>
    </div>
</div>

CameoMvc/CameoMvc/Areas/RPT/Views/RPT001/_List.cshtml
@using CameoMvc.Areas.RPT.Models;
@model M_RPT001

<div>
    <section class="content">
        @if (@Model.LIST_RM.Count > 0)
        {
            if (Model.PHON)
            {
                <div class="row">
                    @foreach (var item in Model.LIST_RM)
                    {
                        var cardStyle = (item.Status == "FAIL") ? "card card-outline card-danger collapsed-card" : (item.ReworkNo == "N/A") ? "card card-outline card-success collapsed-card" : "card card-outline card-info collapsed-card";

                        <div id="divCard" class="@cardStyle">
                            <div class="card-header">
                                <h5 class="card-title">@item.WTime&nbsp;【@item.WUser】</h5>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="收合">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col">工  單：@item.WO</div>
                                </div>
                                <div class="row">
                                    <div class="col">站  點：@item.Terminal</div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">線  別：@item.PdLine</div>
                                </div>
                                <div class="row">
                                    <div class="col">料  號：@item.ItemNo</div>
                                </div>
                                @if (!string.IsNullOrWhiteSpace(item.MAC) && item.MAC != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">ＭＡＣ：@item.MAC</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.CSN) && item.CSN != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">出貨序號：@item.CSN</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.BoxNo) && item.BoxNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">彩盒號：@item.BoxNo</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.CartonNo) && item.CartonNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">外箱號：@item.CartonNo</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.PalletNo) && item.PalletNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">棧板號：@item.PalletNo</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.InspNo) && item.InspNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">送驗單：@item.InspNo</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.QcNo) && item.QcNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">檢驗單：@item.QcNo</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.ReworkNo) && item.ReworkNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">重工單：@item.ReworkNo</div>
                                    </div>
                                }
                                @if (!string.IsNullOrWhiteSpace(item.PanelNo) && item.PanelNo != "N/A")
                                {
                                    <div class="row">
                                        <div class="col">連版號：@item.PanelNo</div>
                                    </div>
                                }
                            </div>
                        </div>
                    }
                </div>
            }
            else
            {
                <div id="divList" class="container-fluid table-responsive-sm" style="overflow: auto; height:260px;">
                    <table class='table table-bordered table-hover table-striped'>
                        <thead class="thead-dark" id="thFix">
                            <tr>
                                <th nowrap="nowrap" style="text-align:center;">工單</th>
                                <th nowrap="nowrap" style="text-align:center;">料號</th>
                                <th nowrap="nowrap" style="text-align:center;">生產線</th>
                                <th nowrap="nowrap" style="text-align:center;">製程</th>
                                <th nowrap="nowrap" style="text-align:center;">站點</th>
                                <th nowrap="nowrap" style="text-align:center;">狀態</th>
                                <th nowrap="nowrap" style="text-align:center;">製程時間</th>
                                <th nowrap="nowrap" style="text-align:center;">作業人員</th>
                                <th nowrap="nowrap" style="text-align:center;">出貨序號</th>
                                <th nowrap="nowrap" style="text-align:center;">MAC位址</th>
                                <th nowrap="nowrap" style="text-align:center;">送驗單號</th>
                                <th nowrap="nowrap" style="text-align:center;">檢驗單號</th>
                                <th nowrap="nowrap" style="text-align:center;">內彩盒號</th>
                                <th nowrap="nowrap" style="text-align:center;">外箱箱號</th>
                                <th nowrap="nowrap" style="text-align:center;">棧板號</th>
                                <th nowrap="nowrap" style="text-align:center;">重工單號</th>
                                <th nowrap="nowrap" style="text-align:center;">連版號</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.LIST_RM)
                            {
                                var style = (item.Status == "FAIL") ? "table-danger" : item.ReworkNo == "N/A" ? "" : "table-info";
                                <tr class="@style">
                                    <td nowrap="nowrap" style="text-align:center;">@item.WO</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.ItemNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.PdLine</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.Process</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.Terminal</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.Status</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.WTime</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.WUser</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.CSN</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.MAC</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.InspNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.QcNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.BoxNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.CartonNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.PalletNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.ReworkNo</td>
                                    <td nowrap="nowrap" style="text-align:center;">@item.PanelNo</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        }
        else
        {
            <div class="pager">
                <table>
                    <tr class="GridEmptyRowStyle">
                        <td>無資料</td>
                    </tr>
                </table>
            </div>
        }
    </section>
</div>

<style type="text/css">
    #tbList thead tr {
        border: 1px solid #ffffff;
    }

        #tbList thead tr th {
            position: sticky;
            top: 0; /* 列首永遠固定於上 */
            border: 1px solid #ffffff;
        }
</style>
<script type="text/javascript">
    $("#divList").height($("#div_content").height() - $("#divCard").outerHeight() - 27);
</script>

CameoMvc/CameoMvc/Areas/RPT/Views/RPT001/_Query.cshtml
@using CameoMvc.Areas.RPT.Models;
@model M_RPT001

@{
    <!-- 抬頭功能名稱 -->
    var TitleText = Model.FUNC_NAME + "(" + Model.FUNC + ")";

    <!-- 判斷是否為行動裝置，以採用對應的樣式 -->
    //預設為展開
    var divCard_Style = "card";
    var imgCard_Style = "fas fa-minus";

    //行動裝置，改為縮合
    if (Model.PHON)
    {
        divCard_Style = "card collapsed-card";
        imgCard_Style = "fas fa-plus";
    }
}

<!-- 是否導入 QR Code Reader -->
<div id="modal-qr" class="modal fade show" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" width="400">
            <div class="modal-header">
                <!-- 選擇影像來源 -->
                <div id="SelectSrc" style="display:none">
                    <label for="sourceSelect">選擇鏡頭</label>
                    <select id="sourceSelect" style="max-width:400px"></select>
                </div>
                <div id="ChangeSrc">
                    <a class="btn btn-app bg-success">
                        <i class="glyphicon glyphicon-refresh"></i>
                        更換鏡頭
                    </a>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="modal-body">
                <video id="video" width="400" height="300"></video>
            </div>
        </div>
    </div>
</div>

<div id="divCard" class="card">
    <div class="card-header bg-gradient-primary">
        <h3 class="card-title">@TitleText</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="收合">
                <i class="fas fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div style="margin-top:2px;"></div>
        <!-- 輸入框 -->
        <!-- 當有多個按鍵時，為了不要直接觸發 Submit，要加入 keypressHandle -->
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="input-group">
                    @Html.TextBoxFor(model => model.QM.SN, new { id = "txt1", name = "qrtxt", @placeholder = "序號", @class = "form-control", @autofocus = "" })
                    <div id="btnScan1" name="txt1" class="input-group-addon" data-toggle="modal" data-target="#modal-qr">
                        <div class="input-group-text">
                            <span class="fas fa-barcode"></span>
                        </div>
                    </div>
                </div>
                @Html.ValidationMessageFor(model => model.QM.SN)
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="input-group">
                    @Html.TextBoxFor(model => model.QM.CSN, new { id = "txt2", name = "qrtxt", @placeholder = "客戶序號", @class = "form-control" })
                    <div id="btnScan2" name="txt2" class="input-group-addon" data-toggle="modal" data-target="#modal-qr">
                        <div class="input-group-text">
                            <span class="fas fa-barcode"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="input-group">
                    @Html.TextBoxFor(model => model.QM.MAC, new { id = "txt3", name = "qrtxt", @placeholder = "MAC", @class = "form-control" })
                    <div id="btnScan3" name="txt3" class="input-group-addon" data-toggle="modal" data-target="#modal-qr">
                        <div class="input-group-text">
                            <span class="fas fa-barcode"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- 按鍵 -->
    <div class="card-footer">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                <button name="button" type="submit" class="btn btn-primary col-12" value="Query">查詢</button>
            </div>
        </div>
    </div>
</div>